<?php

// This is the global social_mediator module. Information that's specific to a individual social network should not be inside this file. 
// This module is shared amongst all the subthemes. 

// need an admin page so that the sub modules have a place to live. 

function social_mediator_menu()
{
  $menu['admin/social'] = array
  (
    'title' => 'Social Mediator',
    'page callback' => '_social_mediator_admin_page',
    'access callback' => TRUE,
  );
  $menu['admin/social/importall'] = array
  (
    'title' => 'Social Mediator',
    'page callback' => '_social_mediator_import',
    'access callback' => TRUE,
  );
  return $menu;
}

// set up global social_mediator permissions.


function _social_mediator_admin_page() {
  $content = array('Here is the admin landing page for the global social mediator.');

  $output = '';
  return $output;
}

// need _function to handle import. This will happen on any imports.

function _social_mediator_import()
{
  $content = array();

  if (sizeof(module_implements('social_mediator_import')) > 0) {
  	$content = module_invoke_all('social_mediator_import', $content);
  } else {
  	$content = array("There are no submodules installed.");
  }

  dsm($content);

  $output = '';
  foreach($content as $c)
  {
    $output .= '<p>' . $c . '</p>';
  }
  return $output;
}

// need hook_cron so that imports happen on cron.