<?php

// This is the global social_mediator module. Information that's specific to a individual social network should not be inside this file. 
// This module is shared amongst all the subthemes. 

// need an admin page so that the sub modules have a place to live. 

function social_mediator_menu() {
  $items = array();

  $items['admin/social'] = array (
    'title' => 'Social Mediator',
    'description' => 'Provide API keys to authenticate with Twitter and Instagram',
    'page callback' => '_social_mediator_admin_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/social/info'] = array (
  	'title' => 'Reports',
    'weight' => -1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/social/importall'] = array (
    'title' => 'Import',
    'page callback' => '_social_mediator_import',
    'access callback' => TRUE,
  );
  return $items;
}

// set up global social_mediator permissions.


function _social_mediator_admin_page() {
  $content = array('Here is the admin landing page for the global social mediator. 
  					There will be a button to force an import.
  					It should also say the last time there was an import, and what was imported.');

  $output = '';
  foreach($content as $c)
  {
    $output .= '<p>' . $c . '</p>';
  }
  return $output;
}

// need _function to handle import. This will happen on any imports.

function _social_mediator_import()
{
  $content = array();

  if (sizeof(module_implements('social_mediator_import')) > 0) {
  	$content = module_invoke_all('social_mediator_import', $content);
  } else {
  	$content = array("There are no submodules installed.");
  }

  //dsm($content);

  $output = '';
  foreach($content as $c)
  {
    $output .= '<p>' . $c . '</p>';
  }
  return $output;
}

// need hook_cron so that imports happen on cron.