<?php

// This is the  twitter specific social_mediator sub-module. Everything in this module should be specific to handling twitter.
// There should be nothing in this module that would be shared with the facebook module. 

function social_mediator_twitter_menu()
{
  $menu['admin/social/twitter'] = array
  (
    'title' => 'Twitter Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_social_mediator_twitter_admin_page'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );

  return $menu;
}

// need a tab in the social_mediator subtheme for twitter. 
function _social_mediator_twitter_admin_page($form, &$form_state) {
  $content = array('Here is the admin landing page for the global social mediator.');

  $form = array();

  // pull tweets from a specific user
  // exclude replies?

  	$form['sm_twitter_method'] = array(
		'#type' => 'radios',
  		'#options' => drupal_map_assoc(array(t('A Twitter User'), t('Specified Hashtag(s)'))),
  		'#title' => t('Pull all tweets from '),
		'#default_value' => variable_get("sm_twitter_method", ""),
		'#required' => TRUE,
	);

	$form['sm_api_user'] = array(
		'#type' => 'fieldset',
		'#title' => t('A Twitter User'),
	);

	$form['sm_api_user']['sm_twitter_handle'] = array(
		'#type' => 'textfield',
		'#title' => t('Username'),
		'#description' => t('The handle of the twitter user.'),
		'#default_value' => variable_get("sm_twitter_handle", "")
	);

	$form['sm_api_user']['sm_twitter_exclude_replies'] = array(
		'#type' => 'checkbox',
		'#title' => t('Exclude Replies'),
		'#description' => t('Do not import this user\'s replies to tweets.'),
		'#default_value' => variable_get("sm_twitter_exclude_replies", "")
	);

	$form['sm_api_hashtag'] = array(
		'#type' => 'fieldset',
		'#title' => t('A Twitter User'),
	);

	$form['sm_api_hashtag']['sm_twitter_hashtag'] = array(
		'#type' => 'textfield',
		'#title' => t('Hashtag(s)'),
		'#description' => t('Import all tweets that use these specified hashtags. Specifiy multiple hashtags by using a comma. Do not include the #.'),
		'#default_value' => variable_get("sm_twitter_hashtag", "")
	);

	$form['sm_api_details'] = array(
		'#type' => 'fieldset',
		'#title' => t('Twitter API details'),
	);

	$form['sm_api_details']['sm_oauth_access_token'] = array(
		'#type' => 'textfield',
		'#title' => t('OAuth Access Token'),
		'#description' => t('Enter your OAuth Access Token'),
		'#default_value' => variable_get("sm_oauth_access_token", ""),
		 '#required' => TRUE,
	);

	$form['sm_api_details']['sm_oauth_access_token_secret'] = array(
		'#type' => 'textfield',
		'#title' => t('OAuth Access Token Secret'),
		'#description' => t('Enter your OAuth Access Secret Token'),
		'#default_value' => variable_get("sm_oauth_access_token_secret", ""),
		 '#required' => TRUE,
	);

	$form['sm_api_details']['sm_twitter_consumer_key'] = array(
		'#type' => 'textfield',
		'#title' => 'Consumer Key',
		'#description' => t('Enter your Consumer Key'),
		'#default_value' => variable_get("sm_twitter_consumer_key", ""),
		 '#required' => TRUE,
	);

	$form['sm_api_details']['sm_twitter_consumer_secret'] = array(
		'#type' => 'textfield',
		'#title' => t('Secret Key'),
		'#description' => t('Enter your Secret Key'),
		'#default_value' => variable_get("sm_twitter_consumer_secret", ""),
		 '#required' => TRUE,
	);

  return system_settings_form($form);
}

// need _function to handle twitter import.
// since it's using a hook of the global module, just keep twitter important stuff.
function social_mediator_twitter_social_mediator_import($content) {
	$content[] = "<h3>Importing Tweets</h3>";

	require_once ('class/TwitterAPIExchange.php');

	/** Set access tokens here - see: https://dev.twitter.com/apps/ **/
	$settings = array(
	    'oauth_access_token' => variable_get("sm_oauth_access_token", ""),
	    'oauth_access_token_secret' => variable_get("sm_oauth_access_token_secret", ""),
	    'consumer_key' => variable_get("sm_twitter_consumer_key", ""),
	    'consumer_secret' => variable_get("sm_twitter_consumer_secret", "")
	);

	$method = variable_get("sm_twitter_method", "");

	if ($method == "Specified Hashtag(s)") {
		$url = 'https://api.twitter.com/1.1/search/tweets.json';

		$hashtags = explode(", ", variable_get("sm_twitter_hashtag", ""));

		$hashtag_string = implode($hashtags, "+%23");

		$getfield = '?q=%23'.$hashtag_string.'&count=10';
	} else if ($method == "A Twitter User") {
		$url = 'https://api.twitter.com/1.1/statuses/user_timeline.json';

		$exclude = false;
		if (variable_get("sm_twitter_exclude_replies", "") == 1) {
			$exclude = true;
		}

		$getfield = '?screen_name='.variable_get("sm_twitter_handle", "").'&count=10&exclude_replies='.$exclude;
	} else {
		$content[] = "Social Mediator Twitter needs to be configured.";
	}

	$requestMethod = 'GET';
	$twitter = new TwitterAPIExchange($settings);
	$results = $twitter->setGetfield($getfield)
	             ->buildOauth($url, $requestMethod)
	             ->performRequest();

	$results = json_decode($results);

	if ($method == "Specified Hashtag(s)") {
		$results = $results->statuses;
	}

	$count = 0;

	foreach ($results as $result) {
		$object = array();
		$object['tweet_content'] = $result->text;
		$object['tweet_id'] = $result->id_str;
		if (isset($result->retweeted_status)) {
			$object['twitter_user'] = $result->retweeted_status->user->name ." (@". $result->retweeted_status->user->screen_name .")";
		} else {
			$object['twitter_user'] = $result->user->name ." (@". $result->user->screen_name .")";
		}
		$object['tweet_date'] = date('m/d/Y H:i:s', strtotime($result->created_at));

		if (_social_mediator_twitter_find_node($object['tweet_id']) != 1) {
			_social_mediator_twitter_create_node($object);
			$content[] = "<strong>Tweet: </strong>" . _social_mediator_removeEmoji($object['tweet_content']);
			$count++;
		}
	}

	if ($count == 0) {
		$content[] = "Tweets are up-to-date.";
	} else {
		$content[] = "Imported ".$count." tweets.";
	}

	return $content;
}

function _social_mediator_twitter_find_node($id) {
	$query = new EntityFieldQuery();

	$query->entityCondition('entity_type', 'node')
	->entityCondition('bundle', 'sm_tweet')
	->fieldCondition('tweet_id', 'value', $id, '=')
	->addMetaData('account', user_load(1));

	$result = $query->execute();

	if (sizeof($result) == 0) {
		return false;
	} else {
		return true;
	}
}	

function _social_mediator_twitter_create_node($object) {
	$node = new StdClass();

	$node->type = 'sm_tweet';
	node_object_prepare($node);

	$node->title = _social_mediator_removeEmoji($object['tweet_content']);

	//$node->tweet_date['und'][0]['value'] = date('Y-m-d H:i:s', strtotime($object['tweet_date']));
	$node->twitter_user['und'][0]['value'] = $object['twitter_user'];
	$node->tweet_content['und'][0]['value'] = _social_mediator_removeEmoji($object['tweet_content']);
	$node->tweet_id['und'][0]['value'] = $object['tweet_id'];

	node_save($node);
}




// need hook_cron so that imports happen on cron.